// vue-chat/src/components/ChatBody.vue
<script setup lang="ts">
import type { IMessage, ITyping } from '../../../models'
import { inject, ref } from 'vue'
import router from '@/router'

const me = localStorage.getItem('userName')
const socket = inject('socket') as any
const messages = ref([] as IMessage[])

const typingStatus = ref('')
socket.on('messageResponse', (data: IMessage) => (messages.value = [...messages.value, data]))
socket.on('typingResponse', (data: ITyping) => (typingStatus.value = data))

function handleLeaveChat() {
  localStorage.removeItem('userName')
  socket.emit('userLeft', {
    userName: me,
    socketID: socket.id
  })
  router.push('/')
}
</script>

<template>
  <header class="chat__mainHeader">
    <p>Hangout with Colleagues</p>

    <button class="leaveChat__btn" @click="handleLeaveChat">LEAVE CHAT</button>
  </header>

  <div class="message__container">
    <div v-for="message in messages" :key="message.text">
      <div class="message__chats" v-if="message.name === me">
        <p class="sender__name">You</p>
        <div class="message__sender">
          <p>{{ message.text }}</p>
        </div>
      </div>

      <div class="message__chats" :key="message.id" v-if="message.name !== me">
        <p>{{ message.name }}</p>
        <div class="message__recipient">
          <p>{{ message.text }}</p>
        </div>
      </div>
    </div>

    <div class="message__status">
      <p>{{ typingStatus }}</p>
    </div>
    <div></div>
  </div>
</template>

// react-chat/src/components/ChatBody.js
import React from "react";
import { useNavigate } from "react-router-dom";

const ChatBody = ({ messages, typingStatus, lastMessageRef, socket }) => {
  const navigate = useNavigate();
  const currentUserName = localStorage.getItem("userName");

  const handleLeaveChat = () => {
    localStorage.removeItem("userName");
    socket.emit("userLeft", { userName: currentUserName, socketID: socket.id });
    navigate("/");
  };

  return (
    <>
      <header className="chat__mainHeader">
        <p>Hangout with Colleagues</p>
        <button className="leaveChat__btn" onClick={handleLeaveChat}>
          LEAVE CHAT
        </button>
      </header>

      <div className="message__container">
        {messages.map((message) => (
          <div className="message__chats" key={message.id}>
            {message.name === currentUserName ? (
              <>
                <p className="sender__name">You</p>
                <div className="message__sender">
                  <p>{message.text}</p>
                </div>
              </>
            ) : (
              <>
                <p>{message.name}</p>
                <div className="message__recipient">
                  <p>{message.text}</p>
                </div>
              </>
            )}
          </div>
        ))}

        <div className="message__status">
          <p>{typingStatus}</p>
        </div>
        <div ref={lastMessageRef} />
      </div>
    </>
  );
};

export default ChatBody;
