// angular-chat/src/app/components/chat-body.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, Input } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'chat-body',
  standalone: true,
  imports: [CommonModule],
  template: ` <header class="chat__mainHeader">
      <p>Hangout with Colleagues</p>
      <button class="leaveChat__btn" (click)="handleLeaveChat()">
        LEAVE CHAT
      </button>
    </header>

    <div class="message__container">
      <ng-container *ngFor="let message of messages">
        <div
          *ngIf="message.name === me; else notMe"
          class="message__chats"
          [attr.key]="message.id"
        >
          <p class="sender__name">You</p>
          <div class="message__sender">
            <p>{{ message.text }}</p>
          </div>
        </div>
        <ng-template #notMe>
          <div class="message__chats" [attr.key]="message.id">
            <p>{{ message.name }}</p>
            <div class="message__recipient">
              <p>{{ message.text }}</p>
            </div>
          </div>
          /</ng-template
        >
      </ng-container>

      <div class="message__status">
        <p>{{ typingStatus }}</p>
      </div>
      <div [attr.ref]="lastMessageRef"></div>
    </div>`,
})
export class ChatBodyComponent {
  @Input() messages: any;
  @Input() typingStatus = 'typingStatus';
  @Input() lastMessageRef = 'lastMessageRef';
  me = localStorage.getItem('userName');

  router = inject(Router);

  handleLeaveChat() {
    localStorage.removeItem('userName');
    this.router.navigate(['/']);
  }
}

// react-chat/src/components/ChatBody.js
import React from "react";
import { useNavigate } from "react-router-dom";

const ChatBody = ({ messages, typingStatus, lastMessageRef }) => {
  const navigate = useNavigate();

  const handleLeaveChat = () => {
    localStorage.removeItem("userName");
    navigate("/");
  };

  return (
    <>
      <header className="chat__mainHeader">
        <p>Hangout with Colleagues</p>
        <button className="leaveChat__btn" onClick={handleLeaveChat}>
          LEAVE CHAT
        </button>
      </header>

      <div className="message__container">
        {messages.map((message) =>
          message.name === localStorage.getItem("userName") ? (
            <div className="message__chats" key={message.id}>
              <p className="sender__name">You</p>
              <div className="message__sender">
                <p>{message.text}</p>
              </div>
            </div>
          ) : (
            <div className="message__chats" key={message.id}>
              <p>{message.name}</p>
              <div className="message__recipient">
                <p>{message.text}</p>
              </div>
            </div>
          )
        )}

        <div className="message__status">
          <p>{typingStatus}</p>
        </div>
        <div ref={lastMessageRef} />
      </div>
    </>
  );
};

export default ChatBody;
