// react-chat/src/components/ChatFooter.js
import React, { useState } from "react";

const ChatFooter = ({ socket }) => {
  const [message, setMessage] = useState("");
  const handleTyping = () =>
    socket.emit("typing", `${localStorage.getItem("userName")} is typing`);

  const handleSendMessage = (e) => {
    e.preventDefault();
    if (message.trim() && localStorage.getItem("userName")) {
      socket.emit("message", {
        text: message,
        name: localStorage.getItem("userName"),
        id: `${socket.id}${Math.random()}`,
        socketID: socket.id,
      });
    }
    setMessage("");
  };
  return (
    <div className="chat__footer">
      <form className="form" onSubmit={handleSendMessage}>
        <input
          type="text"
          placeholder="Write message"
          className="message"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={handleTyping}
        />
        <button className="sendBtn">SEND</button>
      </form>
    </div>
  );
};

export default ChatFooter;

// vue-chat/src/components/ChatFooter.vue
<script setup lang="ts">
import { inject, ref, type Ref } from 'vue'
const socket = inject('socket') as any

let message: Ref<string> = ref('')
const me = localStorage.getItem('userName')

function handleSendMessage(e: any) {
  e.preventDefault()
  if (me !== null) {
    socket.emit('message', {
      text: message.value,
      name: me,
      id: `${socket.id}${Math.random()}`,
      socketID: socket.id
    })
  }
  message.value = ''
}
function handleTyping() {
  if (me !== null) {
    socket.emit('typing', me + ' is typing')
  }
}
</script>
<template>
  <div class="chat__footer">
    <form class="form" @submit="handleSendMessage">
      <input
        type="text"
        placeholder="Write message"
        class="message"
        name="message"
        v-model="message"
        @input="handleTyping"
      />
      <button class="sendBtn" type="submit">SEND</button>
    </form>
  </div>
</template>
